In [2]:
#Importing libraries
import numpy as np
import pandas as pd

In [5]:
# reading data
df = pd.read_csv('/workspaces/data_cleaning_project/data/Cafe Sales.csv')

In [6]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [7]:
#inspecting last few records
df.tail()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [8]:
#data structure
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [9]:
#duplicate records
print(f'Number of duplicated records : {sum(df.duplicated())}')

Number of duplicated records : 0

In [ ]:
# missing records after replacing Error and Unknown
df.isna().sum() * 100/df.shape[0]

Transaction ID       0.00
Item                 3.33
Quantity             1.38
Price Per Unit       1.79
Total Spent          1.73
Payment Method      25.79
Location            32.65
Transaction Date     1.59
dtype: float64

In [14]:
# unique records
df_columns = set(df.columns)
exclude = {'Transaction ID'}
df_columns = df_columns.difference(exclude)

for column in df_columns:
    print(f'{column}:\n{df[column].unique()}',end = '\n\n')

Payment Method:
<StringArray>
['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan]
Length: 6, dtype: str

Total Spent:
<StringArray>
[    '4.0',    '12.0',   'ERROR',    '10.0',    '20.0',     '9.0',    '16.0',
    '15.0',    '25.0',     '8.0',     '5.0',     '3.0',     '6.0',       nan,
 'UNKNOWN',     '2.0',     '1.0',     '7.5',     '4.5',     '1.5']
Length: 20, dtype: str

Location:
<StringArray>
['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR']
Length: 5, dtype: str

Quantity:
<StringArray>
['2', '4', '5', '3', '1', 'ERROR', 'UNKNOWN', nan]
Length: 8, dtype: str

Price Per Unit:
<StringArray>
['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan, 'ERROR', 'UNKNOWN']
Length: 9, dtype: str

Transaction Date:
<StringArray>
['2023-09-08', '2023-05-16', '2023-07-19', '2023-04-27', '2023-06-11',
 '2023-03-31', '2023-10-06', '2023-10-28', '2023-07-28', '2023-12-31',
 ...
 '2023-08-01', '2023-01-20', '2023-11-11', '2023-02-13', '2023-07-30',
 '2023-02-17', '2023-05-20', '2023-11-05', '2023-03-27', '2023-07-03']
Length: 368, dtype: str

Item:
<StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',  'UNKNOWN',
 'Sandwich',        nan,    'ERROR',    'Juice',      'Tea']
Length: 11, dtype: str

In [16]:
#replacing ERROR and Unknown values
df = df.replace(['ERROR','UNKNOWN'],np.nan)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9031 non-null   str
 2   Quantity          9521 non-null   str
 3   Price Per Unit    9467 non-null   str
 4   Total Spent       9498 non-null   str
 5   Payment Method    6822 non-null   str
 6   Location          6039 non-null   str
 7   Transaction Date  9540 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [19]:
df['Quantity'] = df['Quantity'].astype('Int64')
df[['Price Per Unit','Total Spent']] = df[['Price Per Unit','Total Spent']].astype('float')
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9031 non-null   str
 2   Quantity          9521 non-null   Int64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    6822 non-null   str
 6   Location          6039 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: Int64(1), datetime64[us](1), float64(2), str(4)
memory usage: 634.9 KB

In [23]:
#dropping records where Transaction date is not available
df = df.dropna(subset = ['Transaction Date'])

In [24]:
df.info()

<class 'pandas.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   str
 1   Item              8613 non-null   str
 2   Quantity          9086 non-null   Int64
 3   Price Per Unit    9034 non-null   float64
 4   Total Spent       9064 non-null   float64
 5   Payment Method    6525 non-null   str
 6   Location          5761 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: Int64(1), datetime64[us](1), float64(2), str(4)
memory usage: 680.1 KB

In [26]:
# replacing missing records in payment 
df[['Payment Method','Location']] = df[['Payment Method','Location']].fillna('INA')

In [ ]:
df['Item']= df['Item'].fillna(df['Item'].mode()[0])

'Juice'

In [29]:
df.describe()

       Quantity  Price Per Unit  Total Spent            Transaction Date
count    9086.0     9034.000000  9064.000000                        9540
mean   3.025314        2.950022     8.914442  2023-07-01 23:00:31.698113
min         1.0        1.000000     1.000000         2023-01-01 00:00:00
25%         2.0        2.000000     4.000000         2023-04-01 00:00:00
50%         3.0        3.000000     8.000000         2023-07-02 00:00:00
75%         4.0        4.000000    12.000000         2023-10-02 00:00:00
max         5.0        5.000000    25.000000         2023-12-31 00:00:00
std     1.41834        1.277750     6.010311                         NaN

In [31]:
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())

In [32]:
df['Quantity'].median()

np.float64(3.0)

In [33]:
df.groupby('Item')['Price Per Unit'].value_counts()

Item      Price Per Unit
Cake      3.0               1031
Coffee    2.0               1069
Cookie    1.0                976
Juice     3.0               1065
Salad     5.0               1035
Sandwich  4.0               1027
Smoothie  4.0                990
Tea       1.5                965
Name: count, dtype: int64

In [34]:
df['Price Per Unit'].mode()

0    3.0
Name: Price Per Unit, dtype: float64

In [36]:
#filling missing records in price per unit with mode value of item category
df['Price Per Unit'] = df.groupby('Item')['Price Per Unit'].transform(lambda x: x.fillna(x.mode()[0]) )

In [37]:
df.info()

<class 'pandas.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   str
 1   Item              8613 non-null   str
 2   Quantity          9540 non-null   Int64
 3   Price Per Unit    8613 non-null   float64
 4   Total Spent       9064 non-null   float64
 5   Payment Method    9540 non-null   str
 6   Location          9540 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: Int64(1), datetime64[us](1), float64(2), str(4)
memory usage: 680.1 KB

In [38]:
#filling missing records in Total Spent
df['Total Spent'] = df['Total Spent'].fillna(df['Quantity'])*df['Price Per Unit']

In [39]:
df.info()

<class 'pandas.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   str
 1   Item              8613 non-null   str
 2   Quantity          9540 non-null   Int64
 3   Price Per Unit    8613 non-null   float64
 4   Total Spent       8613 non-null   float64
 5   Payment Method    9540 non-null   str
 6   Location          9540 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: Int64(1), datetime64[us](1), float64(2), str(4)
memory usage: 680.1 KB

In [41]:
# saving clean data
df.to_csv('/workspaces/data_cleaning_project/data/Cafe Sales (Cleaned).csv',index=False)